// Generated by CoffeeScript 1.12.4
(function() {
  var comics_lister, path;

  path = require('path');

  comics_lister = function(directory, cb) {
    var comics, finder;
    comics = [];
    finder = require('findit')(directory);
    finder.on('file', function(file, stat) {
      var ref;
      if ((ref = path.extname(file)) === '.cbz' || ref === '.cbr') {
        return comics.push({
          file: file,
          path: path.resolve(file)
        });
      }
    });
    finder.on('end', function() {
      if (cb) {
        return cb(comics);
      } else {
        return console.log(comics);
      }
    });
    return directory;
  };


  /*
  comics_lister process.argv[2] or './contents', (comics) ->
    console.log "First comics: #{comics[0]}"
    console.log "Last comics: #{comics[comics.length - 1]}"
    console.log "\n Total files: #{comics.length}"
   */

  if (typeof module !== "undefined" && module !== null) {
    module.exports = comics_lister;
  }

}).call(this);
